[build]
  # 在 Netlify 构建时，先用 npm ci 进行干净安装，再执行 build 脚本
  command = "npm ci && npm run build"
  # Docusaurus 默认构建产物目录
  publish = "build"

[build.environment]
  # 指定 Node.js 和 npm 版本，保持构建环境一致
  NODE_VERSION = "18"
  NPM_VERSION = "9.7.1"

[context.deploy-preview]
  # 预览环境也使用同样构建命令和产物目录
  command = "npm ci && npm run build"
  publish = "build"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    # 缓存 webpack 构建缓存，提升构建速度
    paths = [
      "node_modules/.cache/webpack"
    ]
