# Netlify file based configuration
# doc: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "build/"

[build.environment]
  NPM_VERSION = "9.7.1"
  NODE_VERSION = "18"

[context.deploy-preview]
  publish = "build/"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]
